import { Category, Website } from '@/types';

export const SEEDED_CATEGORIES: Category[] = [
  { id: 'cat-ai-ml', slug: 'ai-ml', name: 'AI & Machine Learning', description: 'Generative models, LLMs, AI agents, and machine learning platforms', icon: 'Bot', color: 'from-purple-500 to-pink-500' },
  { id: 'cat-dev-tools', slug: 'dev-tools', name: 'Developer Tools', description: 'IDEs, code hosting, CI/CD, and developer productivity suites', icon: 'Code2', color: 'from-blue-500 to-cyan-500' },
  { id: 'cat-design-ui', slug: 'design-ui', name: 'Design & UI/UX', description: 'Interface design, prototyping tools, inspirations, and asset libraries', icon: 'Palette', color: 'from-amber-500 to-rose-500' },
  { id: 'cat-productivity', slug: 'productivity', name: 'Productivity & Workflow', description: 'Notetaking, issue tracking, launchers, and workspace systems', icon: 'Zap', color: 'from-emerald-500 to-teal-500' },
  { id: 'cat-tech-startups', slug: 'tech-startups', name: 'Tech & Startups', description: 'Product launches, accelerators, funding databases, and communities', icon: 'Rocket', color: 'from-orange-500 to-red-500' },
  { id: 'cat-marketing-seo', slug: 'marketing-seo', name: 'Marketing & SEO', description: 'SEO audit suites, keyword discovery, email growth, and marketing automation', icon: 'TrendingUp', color: 'from-pink-500 to-rose-500' },
  { id: 'cat-education', slug: 'education', name: 'Education & Learning', description: 'Interactive coding academies, developer roadmaps, and university certifications', icon: 'GraduationCap', color: 'from-violet-500 to-purple-500' },
  { id: 'cat-open-source', slug: 'open-source', name: 'Open Source', description: 'Community software, open frameworks, developer tools, and BaaS', icon: 'GitBranch', color: 'from-green-500 to-emerald-500' },
  { id: 'cat-utilities-apis', slug: 'utilities-apis', name: 'Utilities & APIs', description: 'Docs browsers, formatters, image compressors, and regex debuggers', icon: 'Cpu', color: 'from-sky-500 to-blue-600' },
  { id: 'cat-media-entertainment', slug: 'media-entertainment', name: 'Media & Entertainment', description: 'Audio streaming, high-res photography, and multimedia assets', icon: 'Film', color: 'from-fuchsia-500 to-purple-600' },
  { id: 'cat-govt-services', slug: 'govt-services', name: 'Govt & Citizen Services', description: 'Official government application portals, passport, NID, birth certificate, BMET, and visa verification platforms', icon: 'Shield', color: 'from-emerald-600 to-teal-700' }
];

export const SEEDED_WEBSITES: Website[] = [
  // --- AI & Machine Learning ---
  {
    id: 'site-chatgpt',
    slug: 'chatgpt',
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    domain: 'chat.openai.com',
    categoryId: 'cat-ai-ml',
    pricing: 'FREEMIUM',
    rating: 4.9,
    upvotes: 1420,
    featured: true,
    description: 'Leading conversational AI model by OpenAI capable of generating code, analysis, and creative writing.',
    longDescription: 'ChatGPT is OpenAI\'s state-of-the-art language model designed for conversational interaction. It assists users with coding, brainstorming, content creation, mathematical reasoning, and complex problem-solving with multimodal capabilities.',
    tags: ['Generative AI', 'Chatbot', 'LLM', 'Productivity'],
    iconBg: '#10a37f',
    iconText: 'GPT',
    bannerGradient: 'linear-gradient(135deg, #10a37f 0%, #0d7a5f 100%)',
    keyFeatures: ['GPT-4o Multimodal Support', 'Custom GPTs Marketplace', 'Code Interpreter & Python execution', 'Voice & Image Understanding'],
    createdAt: '2025-01-10'
  },
  {
    id: 'site-claude',
    slug: 'claude',
    name: 'Claude AI',
    url: 'https://claude.ai',
    domain: 'claude.ai',
    categoryId: 'cat-ai-ml',
    pricing: 'FREEMIUM',
    rating: 4.9,
    upvotes: 1280,
    featured: true,
    description: 'Anthropic\'s next-generation AI assistant built for deep research, coding, and large document analysis.',
    longDescription: 'Claude by Anthropic features massive 200k+ token context windows, state-of-the-art coding abilities, and nuanced, steerable outputs with top-tier safety and reasoning standards.',
    tags: ['AI Assistant', 'Anthropic', 'Coding', 'Research'],
    iconBg: '#d97706',
    iconText: 'CL',
    bannerGradient: 'linear-gradient(135deg, #d97706 0%, #b45309 100%)',
    keyFeatures: ['200K+ Context Window', 'Artifacts interactive preview', 'High precision coding & reasoning', 'Document analysis'],
    createdAt: '2025-01-15'
  },
  {
    id: 'site-midjourney',
    slug: 'midjourney',
    name: 'Midjourney',
    url: 'https://www.midjourney.com',
    domain: 'midjourney.com',
    categoryId: 'cat-ai-ml',
    pricing: 'PAID',
    rating: 4.8,
    upvotes: 980,
    featured: false,
    description: 'Industry-standard generative AI tool creating photorealistic and artistic imagery from prompts.',
    longDescription: 'Midjourney creates stunning, high-resolution imagery and concept art using advanced diffusion models. Popular with artists, designers, and creative directors worldwide.',
    tags: ['Image Generation', 'Art', 'Design', 'Creative'],
    iconBg: '#0f172a',
    iconText: 'MJ',
    bannerGradient: 'linear-gradient(135deg, #3b82f6 0%, #1e1b4b 100%)',
    keyFeatures: ['Hyper-realistic rendering', 'Web editor interface', 'Vary & Inpainting', 'Style reference tuners'],
    createdAt: '2025-02-01'
  },
  {
    id: 'site-huggingface',
    slug: 'huggingface',
    name: 'Hugging Face',
    url: 'https://huggingface.co',
    domain: 'huggingface.co',
    categoryId: 'cat-ai-ml',
    pricing: 'OPEN_SOURCE',
    rating: 4.9,
    upvotes: 1150,
    featured: true,
    description: 'The premier open-source AI community and hub for pre-trained models, datasets, and ML spaces.',
    longDescription: 'The GitHub of Machine Learning. Hugging Face hosts over 500,000 open-source models, interactive Gradio demos, and fine-tuning pipelines for researchers and developers.',
    tags: ['Open Source ML', 'Models', 'Transformers', 'Datasets'],
    iconBg: '#ffbd59',
    iconText: '🤗',
    bannerGradient: 'linear-gradient(135deg, #ffbd59 0%, #ff6b6b 100%)',
    keyFeatures: ['Transformers library', 'Spaces demo hosting', 'Model Hub & Benchmarks', 'AutoTrain & Inference API'],
    createdAt: '2025-01-05'
  },
  {
    id: 'site-v0',
    slug: 'v0-dev',
    name: 'v0 by Vercel',
    url: 'https://v0.dev',
    domain: 'v0.dev',
    categoryId: 'cat-ai-ml',
    pricing: 'FREEMIUM',
    rating: 4.8,
    upvotes: 890,
    featured: false,
    description: 'Generative UI system by Vercel that converts natural language prompts into clean React & Tailwind code.',
    longDescription: 'v0 is an AI-powered UI generator developed by Vercel. It creates production-ready frontend components, pages, and web apps with Tailwind CSS and shadcn/ui on the fly.',
    tags: ['Generative UI', 'React', 'Tailwind', 'Frontend'],
    iconBg: '#000000',
    iconText: 'v0',
    bannerGradient: 'linear-gradient(135deg, #000000 0%, #434343 100%)',
    keyFeatures: ['Instant React & Tailwind export', 'shadcn/ui integration', 'Iterative UI editing', 'Live Code Sandbox'],
    createdAt: '2025-02-10'
  },

  // --- Developer Tools ---
  {
    id: 'site-github',
    slug: 'github',
    name: 'GitHub',
    url: 'https://github.com',
    domain: 'github.com',
    categoryId: 'cat-dev-tools',
    pricing: 'FREEMIUM',
    rating: 4.9,
    upvotes: 1890,
    featured: true,
    description: 'The world\'s largest software development platform for Git version control, CI/CD, and collaboration.',
    longDescription: 'GitHub provides distributed version control, source code management, GitHub Actions for automation, Copilot AI coding, and millions of open source repositories.',
    tags: ['Git', 'Version Control', 'CI/CD', 'Open Source'],
    iconBg: '#24292e',
    iconText: 'GH',
    bannerGradient: 'linear-gradient(135deg, #24292e 0%, #0d1117 100%)',
    keyFeatures: ['GitHub Actions CI/CD', 'GitHub Copilot AI', 'Pull Request reviews', 'GitHub Packages & Pages'],
    createdAt: '2025-01-01'
  },
  {
    id: 'site-vercel',
    slug: 'vercel',
    name: 'Vercel',
    url: 'https://vercel.com',
    domain: 'vercel.com',
    categoryId: 'cat-dev-tools',
    pricing: 'FREEMIUM',
    rating: 4.9,
    upvotes: 1350,
    featured: true,
    description: 'The Frontend Cloud platform for developing, previewing, and shipping lightning-fast web applications.',
    longDescription: 'Vercel is the creator and maintainer of Next.js, providing zero-config deployments, edge computing, serverless databases, analytics, and instant global CDN delivery.',
    tags: ['Hosting', 'Next.js', 'Frontend Cloud', 'Serverless'],
    iconBg: '#000000',
    iconText: '▲',
    bannerGradient: 'linear-gradient(135deg, #111827 0%, #000000 100%)',
    keyFeatures: ['Instant Git deployments', 'Preview URLs for branches', 'Edge Middleware & Functions', 'Integrated Web Analytics'],
    createdAt: '2025-01-08'
  },
  {
    id: 'site-supabase',
    slug: 'supabase',
    name: 'Supabase',
    url: 'https://supabase.com',
    domain: 'supabase.com',
    categoryId: 'cat-dev-tools',
    pricing: 'OPEN_SOURCE',
    rating: 4.9,
    upvotes: 1240,
    featured: true,
    description: 'The open source Firebase alternative providing PostgreSQL databases, Auth, Storage, and Realtime APIs.',
    longDescription: 'Supabase provides a complete backend stack powered by Postgres. Build in a weekend and scale to millions with automatic REST and GraphQL APIs, row-level security, and vector embeddings.',
    tags: ['Backend', 'PostgreSQL', 'Auth', 'Database'],
    iconBg: '#3ecf8e',
    iconText: '⚡',
    bannerGradient: 'linear-gradient(135deg, #3ecf8e 0%, #24b47e 100%)',
    keyFeatures: ['Dedicated Postgres DB', 'Built-in Authentication & RBAC', 'Edge Functions', 'Vector embeddings (pgvector)'],
    createdAt: '2025-01-12'
  },
  {
    id: 'site-cursor',
    slug: 'cursor',
    name: 'Cursor',
    url: 'https://www.cursor.com',
    domain: 'cursor.com',
    categoryId: 'cat-dev-tools',
    pricing: 'FREEMIUM',
    rating: 4.9,
    upvotes: 1520,
    featured: true,
    description: 'The AI-first code editor fork of VS Code built for hyper-productive pair programming.',
    longDescription: 'Cursor is built from the ground up to pair-program with AI. It understands your entire codebase with semantic indexing, provides multi-file edits, and instant terminal command suggestions.',
    tags: ['Code Editor', 'AI Coding', 'VS Code', 'Productivity'],
    iconBg: '#1e293b',
    iconText: '⚡C',
    bannerGradient: 'linear-gradient(135deg, #6366f1 0%, #4338ca 100%)',
    keyFeatures: ['Full codebase indexing', 'Composer multi-file generation', 'Inline AI edits (Cmd+K)', 'VS Code extension compatibility'],
    createdAt: '2025-02-05'
  },
  {
    id: 'site-postman',
    slug: 'postman',
    name: 'Postman',
    url: 'https://www.postman.com',
    domain: 'postman.com',
    categoryId: 'cat-dev-tools',
    pricing: 'FREEMIUM',
    rating: 4.7,
    upvotes: 940,
    featured: false,
    description: 'Collaborative API development, testing, documentation, and mock server platform for engineers.',
    longDescription: 'Postman simplifies every step of the API lifecycle and streamlines collaboration so you can create better APIs faster. Includes automated testing, documentation, and collections.',
    tags: ['API', 'Testing', 'Backend', 'Collaboration'],
    iconBg: '#ff6c37',
    iconText: 'PM',
    bannerGradient: 'linear-gradient(135deg, #ff6c37 0%, #e0531f 100%)',
    keyFeatures: ['API request client', 'Automated test scripting', 'Mock servers & monitors', 'Public & Private workspaces'],
    createdAt: '2025-01-20'
  },

  // --- Design & UI/UX ---
  {
    id: 'site-figma',
    slug: 'figma',
    name: 'Figma',
    url: 'https://www.figma.com',
    domain: 'figma.com',
    categoryId: 'cat-design-ui',
    pricing: 'FREEMIUM',
    rating: 4.9,
    upvotes: 1760,
    featured: true,
    description: 'Collaborative web-based interface design, prototyping, and design systems platform.',
    longDescription: 'Figma is the industry-standard tool for collaborative product design. Features Auto-layout, component variants, Dev Mode, variables, and seamless team collaboration in real time.',
    tags: ['UI/UX', 'Design', 'Prototyping', 'Design Systems'],
    iconBg: '#f24e1e',
    iconText: 'Fg',
    bannerGradient: 'linear-gradient(135deg, #a259ff 0%, #f24e1e 100%)',
    keyFeatures: ['Real-time multiplayer editing', 'Dev Mode inspection', 'Interactive Prototyping', 'Variables & Design Tokens'],
    createdAt: '2025-01-02'
  },
  {
    id: 'site-framer',
    slug: 'framer',
    name: 'Framer',
    url: 'https://www.framer.com',
    domain: 'framer.com',
    categoryId: 'cat-design-ui',
    pricing: 'FREEMIUM',
    rating: 4.8,
    upvotes: 1110,
    featured: true,
    description: 'Design and publish lightning-fast, production websites with no-code canvas and micro-interactions.',
    longDescription: 'Framer combines the freedom of Figma with the power of website publishing. Design responsive websites on a freeform canvas and ship with CMS, custom animations, and zero code.',
    tags: ['No Code', 'Web Builder', 'Animation', 'CMS'],
    iconBg: '#0055ff',
    iconText: 'Fr',
    bannerGradient: 'linear-gradient(135deg, #0055ff 0%, #003bb5 100%)',
    keyFeatures: ['Figma-to-HTML copy paste', 'Built-in CMS & localization', 'Scroll & 3D micro-animations', 'High SEO performance'],
    createdAt: '2025-01-22'
  },
  {
    id: 'site-dribbble',
    slug: 'dribbble',
    name: 'Dribbble',
    url: 'https://dribbble.com',
    domain: 'dribbble.com',
    categoryId: 'cat-design-ui',
    pricing: 'FREEMIUM',
    rating: 4.6,
    upvotes: 820,
    featured: false,
    description: 'Design community showcase to discover and connect with top designers and creative work.',
    longDescription: 'Dribbble is where millions of designers share screenshots of their work, process, and current projects. A great source for UI/UX inspiration, typography, branding, and motion design.',
    tags: ['Inspiration', 'Graphic Design', 'Portfolio', 'Showcase'],
    iconBg: '#ea4c89',
    iconText: 'Dr',
    bannerGradient: 'linear-gradient(135deg, #ea4c89 0%, #c32361 100%)',
    keyFeatures: ['Inspiration feed by categories', 'Designer portfolios', 'Design jobs board', 'Color palette search'],
    createdAt: '2025-01-18'
  },
  {
    id: 'site-mobbin',
    slug: 'mobbin',
    name: 'Mobbin',
    url: 'https://mobbin.com',
    domain: 'mobbin.com',
    categoryId: 'cat-design-ui',
    pricing: 'FREEMIUM',
    rating: 4.8,
    upvotes: 790,
    featured: false,
    description: 'The world\'s largest mobile & web design reference library with thousands of real app screenshots.',
    longDescription: 'Mobbin is a curated library of mobile and web design patterns from top iOS, Android, and Web apps. Save hours of UI/UX research with comprehensive UX flow breakdowns.',
    tags: ['UI Patterns', 'Mobile Design', 'UX Research', 'Inspiration'],
    iconBg: '#111827',
    iconText: 'Mb',
    bannerGradient: 'linear-gradient(135deg, #374151 0%, #111827 100%)',
    keyFeatures: ['Thousands of real app screens', 'Flow-by-flow navigation patterns', 'Filter by UI element & pattern', 'High-res exports'],
    createdAt: '2025-02-03'
  },

  // --- Productivity & Workflow ---
  {
    id: 'site-notion',
    slug: 'notion',
    name: 'Notion',
    url: 'https://www.notion.so',
    domain: 'notion.so',
    categoryId: 'cat-productivity',
    pricing: 'FREEMIUM',
    rating: 4.9,
    upvotes: 1680,
    featured: true,
    description: 'The all-in-one connected workspace for notes, docs, knowledge bases, and project management.',
    longDescription: 'Notion combines notes, docs, wikis, and project databases with AI superpowers. Customize your workflow, build Kanban boards, roadmap trackers, and collaborative team wikis.',
    tags: ['Notes', 'Wikis', 'Project Management', 'Collaboration'],
    iconBg: '#000000',
    iconText: 'N',
    bannerGradient: 'linear-gradient(135deg, #27272a 0%, #09090b 100%)',
    keyFeatures: ['Flexible database blocks', 'Notion AI summarizer & writer', 'Custom templates & automation', 'Sync across all devices'],
    createdAt: '2025-01-04'
  },
  {
    id: 'site-linear',
    slug: 'linear',
    name: 'Linear',
    url: 'https://linear.app',
    domain: 'linear.app',
    categoryId: 'cat-productivity',
    pricing: 'FREEMIUM',
    rating: 4.9,
    upvotes: 1470,
    featured: true,
    description: 'Streamlined, lightning-fast issue tracking and product roadmaps built for high-performance teams.',
    longDescription: 'Linear is the issue tracker modern software teams love. Built for speed with keyboard-first navigation, automated cycles, Git integrations, and clean minimal design.',
    tags: ['Issue Tracking', 'Agile', 'Productivity', 'Startups'],
    iconBg: '#5e6ad2',
    iconText: 'Ln',
    bannerGradient: 'linear-gradient(135deg, #5e6ad2 0%, #4338ca 100%)',
    keyFeatures: ['Sub-50ms sync speed', 'Keyboard shortcuts for everything', 'Cycles & Roadmap milestones', 'GitHub & Slack 2-way sync'],
    createdAt: '2025-01-09'
  },
  {
    id: 'site-raycast',
    slug: 'raycast',
    name: 'Raycast',
    url: 'https://www.raycast.com',
    domain: 'raycast.com',
    categoryId: 'cat-productivity',
    pricing: 'FREEMIUM',
    rating: 4.9,
    upvotes: 1390,
    featured: true,
    description: 'Blazingly fast, extendable launcher for Mac and Windows that lets you control your tools with hotkeys.',
    longDescription: 'Raycast replaces traditional spotlights with a powerful launcher. Run scripts, manage clipboard history, search docs, control Spotify, and interact with AI in a flash.',
    tags: ['Launcher', 'Mac Utility', 'Hotkeys', 'Extensions'],
    iconBg: '#ff6363',
    iconText: 'Rc',
    bannerGradient: 'linear-gradient(135deg, #ff6363 0%, #dc2626 100%)',
    keyFeatures: ['Extensive Store of 1000+ extensions', 'Raycast AI built-in', 'Clipboard history manager', 'Custom Quicklinks & Snippets'],
    createdAt: '2025-01-14'
  },
  {
    id: 'site-obsidian',
    slug: 'obsidian',
    name: 'Obsidian',
    url: 'https://obsidian.md',
    domain: 'obsidian.md',
    categoryId: 'cat-productivity',
    pricing: 'FREE',
    rating: 4.9,
    upvotes: 1220,
    featured: false,
    description: 'A powerful, private knowledge base on top of a local folder of plain text Markdown files.',
    longDescription: 'Obsidian is a knowledge base that works on local Markdown files. Build a second brain with bi-directional linking, interactive graph views, and a rich plugin ecosystem.',
    tags: ['Second Brain', 'Markdown', 'Local First', 'PKM'],
    iconBg: '#7c3aed',
    iconText: 'Ob',
    bannerGradient: 'linear-gradient(135deg, #7c3aed 0%, #5b21b6 100%)',
    keyFeatures: ['100% local-first & offline data', 'Interactive graph visualization', 'Bi-directional linking', '1500+ Community plugins'],
    createdAt: '2025-01-25'
  },

  // --- Tech & Startups ---
  {
    id: 'site-producthunt',
    slug: 'producthunt',
    name: 'Product Hunt',
    url: 'https://www.producthunt.com',
    domain: 'producthunt.com',
    categoryId: 'cat-tech-startups',
    pricing: 'FREE',
    rating: 4.7,
    upvotes: 1050,
    featured: true,
    description: 'The go-to place for discovering and launching the newest apps, software, and tech products.',
    longDescription: 'Product Hunt surfaces the best new products in tech every day. Founders launch products, collect community feedback, gain early adopters, and compete for Product of the Day.',
    tags: ['Launch Platform', 'Startups', 'Tech News', 'Community'],
    iconBg: '#da552f',
    iconText: 'PH',
    bannerGradient: 'linear-gradient(135deg, #da552f 0%, #b83b19 100%)',
    keyFeatures: ['Daily top product leaderboard', 'Community discussions & reviews', 'Makers portal', 'Newsletter & Awards'],
    createdAt: '2025-01-03'
  },
  {
    id: 'site-ycombinator',
    slug: 'ycombinator',
    name: 'Y Combinator',
    url: 'https://www.ycombinator.com',
    domain: 'ycombinator.com',
    categoryId: 'cat-tech-startups',
    pricing: 'FREE',
    rating: 4.9,
    upvotes: 1180,
    featured: true,
    description: 'World renowned startup accelerator funding startups and publishing invaluable startup advice.',
    longDescription: 'Y Combinator has funded Airbnb, Stripe, Dropbox, Reddit, and thousands more. Provides Startup School, library of founder essays, directory of YC companies, and Hacker News.',
    tags: ['Accelerator', 'Venture Capital', 'Hacker News', 'Founders'],
    iconBg: '#ff6600',
    iconText: 'YC',
    bannerGradient: 'linear-gradient(135deg, #ff6600 0%, #d95300 100%)',
    keyFeatures: ['Startup School free courses', 'YC Startup Directory', 'Hacker News aggregator', 'Investor & Co-founder matching'],
    createdAt: '2025-01-07'
  },

  // --- Marketing & SEO ---
  {
    id: 'site-ahrefs',
    slug: 'ahrefs',
    name: 'Ahrefs',
    url: 'https://ahrefs.com',
    domain: 'ahrefs.com',
    categoryId: 'cat-marketing-seo',
    pricing: 'PAID',
    rating: 4.8,
    upvotes: 830,
    featured: true,
    description: 'All-in-one SEO toolset for backlink analysis, keyword research, competitor audits, and ranking.',
    longDescription: 'Ahrefs crawls the web and stores an immense database of search queries and backlinks. Optimize your website, analyze competitor keywords, and track search ranking progress.',
    tags: ['SEO', 'Keyword Research', 'Backlinks', 'Traffic'],
    iconBg: '#0062ff',
    iconText: 'Ah',
    bannerGradient: 'linear-gradient(135deg, #0062ff 0%, #0044b3 100%)',
    keyFeatures: ['Site Explorer backlink checker', 'Keywords Explorer tool', 'Site Audit crawler', 'Rank Tracker'],
    createdAt: '2025-01-16'
  },
  {
    id: 'site-semrush',
    slug: 'semrush',
    name: 'Semrush',
    url: 'https://www.semrush.com',
    domain: 'semrush.com',
    categoryId: 'cat-marketing-seo',
    pricing: 'FREEMIUM',
    rating: 4.7,
    upvotes: 740,
    featured: false,
    description: 'Leading online visibility management and content marketing SaaS platform.',
    longDescription: 'Semrush offers solutions for SEO, PPC, content marketing, competitive research, and social media management from one dashboard.',
    tags: ['SEO', 'Marketing', 'PPC', 'Content Strategy'],
    iconBg: '#ff642d',
    iconText: 'Sr',
    bannerGradient: 'linear-gradient(135deg, #ff642d 0%, #cf4a18 100%)',
    keyFeatures: ['Competitor domain overview', 'PPC keyword tool', 'Content marketing toolkit', 'Social media scheduler'],
    createdAt: '2025-01-28'
  },

  // --- Education & Learning ---
  {
    id: 'site-freecodecamp',
    slug: 'freecodecamp',
    name: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org',
    domain: 'freecodecamp.org',
    categoryId: 'cat-education',
    pricing: 'FREE',
    rating: 5.0,
    upvotes: 1740,
    featured: true,
    description: 'Free, open community where millions learn to code with hands-on projects and verified certifications.',
    longDescription: 'freeCodeCamp is a non-profit organization offering completely free courses in Responsive Web Design, JavaScript, Python, Data Science, and Machine Learning.',
    tags: ['Learn to Code', 'Full Stack', 'Certifications', 'Free'],
    iconBg: '#0a0a23',
    iconText: '( ; )',
    bannerGradient: 'linear-gradient(135deg, #0a0a23 0%, #1b1b32 100%)',
    keyFeatures: ['Thousands of interactive coding challenges', 'Verified certificates', 'Active global community', 'YouTube video courses'],
    createdAt: '2025-01-06'
  },
  {
    id: 'site-roadmap',
    slug: 'roadmap-sh',
    name: 'roadmap.sh',
    url: 'https://roadmap.sh',
    domain: 'roadmap.sh',
    categoryId: 'cat-education',
    pricing: 'OPEN_SOURCE',
    rating: 4.9,
    upvotes: 1410,
    featured: true,
    description: 'Community-driven developer roadmaps, career paths, and study guides for any tech role.',
    longDescription: 'roadmap.sh is a comprehensive collection of visual interactive roadmaps, guides, and learning paths for Frontend, Backend, DevOps, AI, Blockchain, and Cybersecurity.',
    tags: ['Roadmaps', 'Career Path', 'Study Guide', 'Dev Skills'],
    iconBg: '#0f172a',
    iconText: '🗺️',
    bannerGradient: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
    keyFeatures: ['Visual interactive skill trees', 'Frontend, Backend, DevOps paths', 'Track your progress checklist', 'Community curated resources'],
    createdAt: '2025-01-11'
  },

  // --- Open Source ---
  {
    id: 'site-tailwind',
    slug: 'tailwindcss',
    name: 'Tailwind CSS',
    url: 'https://tailwindcss.com',
    domain: 'tailwindcss.com',
    categoryId: 'cat-open-source',
    pricing: 'OPEN_SOURCE',
    rating: 4.9,
    upvotes: 1620,
    featured: true,
    description: 'A utility-first CSS framework packed with classes that can be composed to build any design.',
    longDescription: 'Tailwind CSS is an open source utility-first CSS framework. It generates only the CSS you actually use, provides responsive design modifiers, dark mode, and endless extensibility.',
    tags: ['CSS', 'Frontend', 'Styling', 'UI Framework'],
    iconBg: '#0ea5e9',
    iconText: '🌊',
    bannerGradient: 'linear-gradient(135deg, #0ea5e9 0%, #0284c7 100%)',
    keyFeatures: ['Utility-first classes', 'Just-In-Time compiler', 'Dark mode & variant states', 'Tailwind UI ecosystem'],
    createdAt: '2025-01-05'
  },
  {
    id: 'site-excalidraw',
    slug: 'excalidraw',
    name: 'Excalidraw',
    url: 'https://excalidraw.com',
    domain: 'excalidraw.com',
    categoryId: 'cat-open-source',
    pricing: 'OPEN_SOURCE',
    rating: 4.9,
    upvotes: 1310,
    featured: true,
    description: 'Virtual collaborative whiteboard for sketching hand-drawn like diagrams and system architectures.',
    longDescription: 'Excalidraw is a free, open-source sketching and whiteboarding canvas. Perfect for architecture diagrams, wireframes, and quick brainstorm sketches with end-to-end encryption.',
    tags: ['Whiteboard', 'Diagrams', 'Architecture', 'Sketch'],
    iconBg: '#6965db',
    iconText: '✏️',
    bannerGradient: 'linear-gradient(135deg, #6965db 0%, #4f46e5 100%)',
    keyFeatures: ['Hand-drawn aesthetic', 'Live peer-to-peer collaboration', 'End-to-end encrypted rooms', 'Export to SVG/PNG'],
    createdAt: '2025-01-19'
  },

  // --- Utilities & APIs ---
  {
    id: 'site-devdocs',
    slug: 'devdocs',
    name: 'DevDocs',
    url: 'https://devdocs.io',
    domain: 'devdocs.io',
    categoryId: 'cat-utilities-apis',
    pricing: 'FREE',
    rating: 4.9,
    upvotes: 1190,
    featured: true,
    description: 'Fast, offline, and unified documentation browser combining 100+ API docs in a clean interface.',
    longDescription: 'DevDocs combines multiple API documentations in a fast, organized, and searchable interface. Includes full offline support, dark theme, and keyboard shortcuts.',
    tags: ['Documentation', 'CheatSheet', 'Offline', 'Reference'],
    iconBg: '#34495e',
    iconText: 'DD',
    bannerGradient: 'linear-gradient(135deg, #34495e 0%, #2c3e50 100%)',
    keyFeatures: ['Instant offline search across 100+ docs', 'Dark mode support', 'Keyboard navigation', 'Zero trackers'],
    createdAt: '2025-01-13'
  },
  {
    id: 'site-regex101',
    slug: 'regex101',
    name: 'Regex101',
    url: 'https://regex101.com',
    domain: 'regex101.com',
    categoryId: 'cat-utilities-apis',
    pricing: 'FREE',
    rating: 4.9,
    upvotes: 1370,
    featured: true,
    description: 'Online regular expression tester, debugger, and code generator with detailed syntax breakdowns.',
    longDescription: 'Regex101 allows you to test, debug, and explain regular expressions in PCRE, JavaScript, Python, and Go flavors with real-time match visualization.',
    tags: ['Regex', 'Debugging', 'Testing', 'Developer'],
    iconBg: '#1e3a8a',
    iconText: '.*',
    bannerGradient: 'linear-gradient(135deg, #1e3a8a 0%, #172554 100%)',
    keyFeatures: ['Real-time regex regex explanation', 'Match group highlights', 'Regex code generator in 6+ languages', 'Community regex library'],
    createdAt: '2025-01-17'
  },

  // --- Media & Entertainment ---
  {
    id: 'site-spotify',
    slug: 'spotify',
    name: 'Spotify Web Player',
    url: 'https://open.spotify.com',
    domain: 'spotify.com',
    categoryId: 'cat-media-entertainment',
    pricing: 'FREEMIUM',
    rating: 4.8,
    upvotes: 1100,
    featured: true,
    description: 'Listen to millions of songs, podcasts, and curated focus playlists directly from your browser.',
    longDescription: 'Spotify Web Player offers on-demand music and podcast streaming with algorithmic recommendations, personalized Discover Weekly lists, and focus background tracks.',
    tags: ['Music', 'Streaming', 'Podcasts', 'Audio'],
    iconBg: '#1ed760',
    iconText: 'Sp',
    bannerGradient: 'linear-gradient(135deg, #1ed760 0%, #159c44 100%)',
    keyFeatures: ['Millions of tracks & podcasts', 'Coding and focus playlists', 'Cross-device sync', 'Personalized daily mixes'],
    createdAt: '2025-01-23'
  },
  {
    id: 'site-unsplash',
    slug: 'unsplash',
    name: 'Unsplash',
    url: 'https://unsplash.com',
    domain: 'unsplash.com',
    categoryId: 'cat-media-entertainment',
    pricing: 'FREEMIUM',
    rating: 4.8,
    upvotes: 1260,
    featured: true,
    description: 'Over 3 million curated, high-resolution royalty-free photos generously donated by global photographers.',
    longDescription: 'Unsplash provides beautiful, free images and photos that you can download and use for any project. Better than any royalty free or stock photos.',
    tags: ['Stock Photos', 'Photography', 'Free Assets', 'Creative'],
    iconBg: '#000000',
    iconText: 'Un',
    bannerGradient: 'linear-gradient(135deg, #1f2937 0%, #000000 100%)',
    keyFeatures: ['Over 3M high-res photos', 'Free for commercial and personal use', 'Unsplash API for developers', 'Curated collections'],
    createdAt: '2025-01-14'
  }
];
