import { PrismaClient, Pricing } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🚀 Seeding Bangladeshi Government Application Portals & Visa Validity Portals into Neon PostgreSQL...')

  // 1. Create or ensure the "Govt & Citizen Services" category
  const govtCategory = await prisma.category.upsert({
    where: { slug: 'govt-services' },
    update: {
      name: 'Govt & Citizen Services',
      description: 'Official government application portals, passport, NID, birth certificate, BMET, and visa verification platforms.',
      icon: 'Shield',
      color: 'from-emerald-600 to-teal-700',
    },
    create: {
      id: 'cat-govt-services',
      slug: 'govt-services',
      name: 'Govt & Citizen Services',
      description: 'Official government application portals, passport, NID, birth certificate, BMET, and visa verification platforms.',
      icon: 'Shield',
      color: 'from-emerald-600 to-teal-700',
    },
  })

  console.log(`✅ Category ensured: ${govtCategory.name} (${govtCategory.slug})`)

  // 2. Define the authentic websites data
  const bangladeshWebsites = [
    {
      slug: 'bd-epassport',
      name: 'Bangladesh e-Passport Online Portal',
      url: 'https://www.epassport.gov.bd',
      domain: 'epassport.gov.bd',
      categoryId: govtCategory.id,
      pricing: Pricing.FREE,
      rating: 4.9,
      upvotes: 1850,
      featured: true,
      description: 'Official Department of Immigration and Passports (DIP) portal for Bangladeshi citizen e-Passport application, renewal, and status tracking.',
      longDescription: 'The official e-Passport portal by the Department of Immigration and Passports (DIP), Government of the People\'s Republic of Bangladesh. Apply online for 5-year or 10-year e-Passports, track your real-time application processing status, calculate official government fees, schedule biometrics appointments, and find passport offices across Bangladesh and foreign missions worldwide.',
      tags: ['Bangladesh', 'e-Passport', 'DIP', 'Govt Portal', 'Online Application', 'Immigration'],
      iconBg: '#059669',
      iconText: '🛂',
      bannerGradient: 'linear-gradient(135deg, #059669 0%, #064e3b 100%)',
      keyFeatures: [
        'Online 5 & 10 Year e-Passport Application & Renewal',
        'Live Application Status Tracking (By Application ID)',
        'Appointment Slot Booking for Biometrics & Photos',
        'Official Fees Calculator & Online Payment Slips',
      ],
    },
    {
      slug: 'bd-smart-nid',
      name: 'Bangladesh Smart NID Card Services',
      url: 'https://services.nidw.gov.bd',
      domain: 'services.nidw.gov.bd',
      categoryId: govtCategory.id,
      pricing: Pricing.FREE,
      rating: 4.8,
      upvotes: 1620,
      featured: true,
      description: 'Official Bangladesh Election Commission NID Wing portal to download digital NID copy, apply for correction, and check Smart Card status.',
      longDescription: 'The National Identity Registration Wing (NIDW) of Bangladesh Election Commission provides citizen-facing digital services including downloading official National ID (NID) digital copies, applying for NID data corrections and re-issues, checking Smart NID card distribution status, voter transfer, and online new voter registration.',
      tags: ['Bangladesh', 'NID', 'Election Commission', 'Smart Card', 'Voter Services', 'Govt Portal'],
      iconBg: '#0284c7',
      iconText: '🆔',
      bannerGradient: 'linear-gradient(135deg, #0284c7 0%, #0369a1 100%)',
      keyFeatures: [
        'Download Official National Identity Card (NID) PDF',
        'NID Information Correction & Re-issue Application',
        'Smart National Identity Card Status & Distribution Check',
        'New Voter Registration & Face Verification Portal',
      ],
    },
    {
      slug: 'bd-bdris-birth-certificate',
      name: 'Birth & Death Registration (BDRIS)',
      url: 'https://bdris.gov.bd',
      domain: 'bdris.gov.bd',
      categoryId: govtCategory.id,
      pricing: Pricing.FREE,
      rating: 4.7,
      upvotes: 1490,
      featured: true,
      description: 'Official Government of Bangladesh system for applying, verifying 17-digit digital birth certificates, and requesting information corrections.',
      longDescription: 'The Birth and Death Registration Information System (BDRIS) managed by Local Government Division, Bangladesh enables citizens to apply for new birth certificates, verify existing 17-digit birth certificates online via QR code, request spelling and date-of-birth corrections, track application status, and obtain authorized civic documents.',
      tags: ['Bangladesh', 'Birth Certificate', 'BDRIS', 'Citizen Services', 'Govt Portal'],
      iconBg: '#10b981',
      iconText: '📜',
      bannerGradient: 'linear-gradient(135deg, #10b981 0%, #047857 100%)',
      keyFeatures: [
        'Online Birth Certificate Application & Verification',
        'Verify 17-Digit Digital Birth Certificate Online',
        'Apply for Correction of Birth & Death Records',
        'Application Tracking & Ward / Union Parishad Submission',
      ],
    },
    {
      slug: 'bd-bmet-manpower',
      name: 'BMET Official Portal',
      url: 'http://www.bmet.gov.bd',
      domain: 'bmet.gov.bd',
      categoryId: govtCategory.id,
      pricing: Pricing.FREE,
      rating: 4.8,
      upvotes: 1730,
      featured: true,
      description: 'Official Bureau of Manpower, Employment and Training portal for overseas employment clearance, migrant registration, and worker protection.',
      longDescription: 'Bureau of Manpower, Employment and Training (BMET) under the Ministry of Expatriates\' Welfare and Overseas Employment coordinates foreign employment processing, mandatory immigration clearance smart cards, skill training via Technical Training Centers (TTCs), Pre-Departure Briefings (PDO), and welfare protection for Bangladeshi expatriates.',
      tags: ['Bangladesh', 'BMET', 'Manpower Clearance', 'Expatriate', 'Overseas Employment', 'Smart Card'],
      iconBg: '#8b5cf6',
      iconText: '🇧🇩',
      bannerGradient: 'linear-gradient(135deg, #8b5cf6 0%, #6d28d9 100%)',
      keyFeatures: [
        'BMET Database Registration for Overseas Workers',
        'Immigration Clearance Smart Card Verification',
        'Overseas Job Offer & Visa Clearance Verification',
        'Technical Training Centers (TTC) & PDO Schedules',
      ],
    },
    {
      slug: 'ami-probashi',
      name: 'Ami Probashi Portal & App',
      url: 'https://amiprobashi.com',
      domain: 'amiprobashi.com',
      categoryId: govtCategory.id,
      pricing: Pricing.FREEMIUM,
      rating: 4.9,
      upvotes: 1980,
      featured: true,
      description: 'Government-approved digital platform for Bangladeshi migrant workers to register for BMET, book mandatory PDO training, and verify overseas jobs.',
      longDescription: 'Ami Probashi is the comprehensive digital portal and mobile application officially authorized by the Ministry of Expatriates\' Welfare and BMET. Migrant workers can register in the BMET database, complete mandatory Pre-Departure Orientation (PDO) bookings, search government-verified overseas job offers, and access airport welfare services directly.',
      tags: ['Bangladesh', 'BMET', 'Ami Probashi', 'Expatriate', 'Visa Processing', 'Recruitment'],
      iconBg: '#f59e0b',
      iconText: '✈️',
      bannerGradient: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
      keyFeatures: [
        'Complete BMET Registration directly from mobile or web',
        'Book Mandatory Pre-Departure Orientation (PDO) Sessions',
        'Search Verified Government-Approved Overseas Jobs',
        'Airport Assistance & Digital Welfare Fund Services',
      ],
    },
    {
      slug: 'muqeem-saudi-visa-check',
      name: 'Muqeem Saudi Visa & Iqama Platform',
      url: 'https://muqeem.sa',
      domain: 'muqeem.sa',
      categoryId: govtCategory.id,
      pricing: Pricing.FREE,
      rating: 4.9,
      upvotes: 2150,
      featured: true,
      description: 'Official Saudi electronic platform to verify exit re-entry visa validity, check Iqama validity, and validate residency status without login.',
      longDescription: 'Muqeem (مقيم) is the official electronic service platform operated by Elm for the Ministry of Interior in the Kingdom of Saudi Arabia. It offers instant public tools to check Exit Re-Entry (Khuruj Awda) visa validity, Iqama expiry dates, Final Exit visa status, and official residency verification using Iqama Number or Visa Number.',
      tags: ['Saudi Arabia', 'Muqeem', 'Iqama Check', 'Exit Re-entry Visa', 'Visa Validity', 'Absher'],
      iconBg: '#059669',
      iconText: '🇸🇦',
      bannerGradient: 'linear-gradient(135deg, #059669 0%, #064e3b 100%)',
      keyFeatures: [
        'Check Saudi Exit Re-Entry (Khuruj Awda) Visa Validity',
        'Verify Iqama Number & Expiry Date Instantly',
        'Check Final Exit (Khuruj Nihai) Visa Status',
        'Validate Official Saudi Residence & Visa Documents',
      ],
    },
    {
      slug: 'saudi-mofa-visa-platform',
      name: 'KSA Visa (Saudi MOFA Visa Platform)',
      url: 'https://visa.mofa.gov.sa',
      domain: 'visa.mofa.gov.sa',
      categoryId: govtCategory.id,
      pricing: Pricing.FREE,
      rating: 4.8,
      upvotes: 1890,
      featured: true,
      description: 'Official Ministry of Foreign Affairs (MOFA) Saudi visa platform for tracking work, family visit, and tourist visa applications and stamping status.',
      longDescription: 'The Saudi Ministry of Foreign Affairs (MOFA) National Visa Platform (formerly Enjaz) enables travelers, recruitment agencies, and expatriates to search visa applications, verify visa approvals, check electronic work visa endorsements (Wakalah), track medical reports, and pay consular visa fees.',
      tags: ['Saudi Arabia', 'MOFA', 'Visa Check', 'Enjaz', 'Work Visa', 'Visit Visa'],
      iconBg: '#1e3a8a',
      iconText: '🏛️',
      bannerGradient: 'linear-gradient(135deg, #1e3a8a 0%, #172554 100%)',
      keyFeatures: [
        'Track Saudi Visa Application & Stamping Status',
        'Enjaz Document & Visa Fee Payment Verification',
        'Family, Personal, & Business Visit Visa Approval Check',
        'Verify Electronic Visa Delegations (Wakalah) for Recruitment',
      ],
    },
    {
      slug: 'wafid-gamca-medical-check',
      name: 'Wafid (GAMCA) GCC Medical Check',
      url: 'https://wafid.com',
      domain: 'wafid.com',
      categoryId: govtCategory.id,
      pricing: Pricing.PAID,
      rating: 4.7,
      upvotes: 1420,
      featured: true,
      description: 'Official GCC Health Council (GAMCA) platform to book and verify mandatory pre-departure medical fitness reports for Saudi Arabia and Gulf countries.',
      longDescription: 'Wafid (formerly GAMCA) is the official electronic medical examination platform managed by the Gulf Health Council. Candidates traveling for work or residency to Saudi Arabia, UAE, Qatar, Oman, Bahrain, or Kuwait must book their mandatory medical examination appointment and verify their Fit/Unfit medical test results online through Wafid.',
      tags: ['Saudi Arabia', 'Wafid', 'GAMCA', 'Medical Check', 'GCC Visa', 'Work Permit'],
      iconBg: '#dc2626',
      iconText: '🏥',
      bannerGradient: 'linear-gradient(135deg, #dc2626 0%, #991b1b 100%)',
      keyFeatures: [
        'Book Mandatory GCC Pre-Employment Medical Examination',
        'Instant Online Fit / Unfit Medical Status Check',
        'Locate Authorized GAMCA Medical Centers in Bangladesh',
        'Download Barcoded Medical Slip for Embassy Visa Stamping',
      ],
    },
    {
      slug: 'bd-brta-service-portal',
      name: 'BRTA Service Portal (BSP)',
      url: 'https://bsp.brta.gov.bd',
      domain: 'bsp.brta.gov.bd',
      categoryId: govtCategory.id,
      pricing: Pricing.FREE,
      rating: 4.6,
      upvotes: 1120,
      featured: false,
      description: 'Official Bangladesh Road Transport Authority (BRTA) digital portal for driving license, learner license, vehicle registration, and tax token payment.',
      longDescription: 'The BRTA Service Portal (BSP) provides integrated transport services for Bangladesh citizens, including online Learner Driving License (LDL) tests, Smart Card Driving License application and delivery tracking, motor vehicle fitness renewal, online digital Tax Token issuance, and vehicle ownership transfer.',
      tags: ['Bangladesh', 'BRTA', 'Driving License', 'Vehicle Registration', 'Tax Token', 'Govt Portal'],
      iconBg: '#047857',
      iconText: '🚗',
      bannerGradient: 'linear-gradient(135deg, #047857 0%, #064e3b 100%)',
      keyFeatures: [
        'Smart Card Driving License Application & Status Tracking',
        'Learner Driving License (LDL) Online Exam & Approval',
        'Motor Vehicle Fitness & Digital Tax Token Renewal',
        'Online Ownership Transfer & Route Permit Application',
      ],
    },
    {
      slug: 'bd-surokkha-vaccine-portal',
      name: 'Surokkha Vaccine & Health Certificate',
      url: 'https://surokkha.gov.bd',
      domain: 'surokkha.gov.bd',
      categoryId: govtCategory.id,
      pricing: Pricing.FREE,
      rating: 4.8,
      upvotes: 1240,
      featured: false,
      description: 'Official Bangladesh Government health portal to download and verify international QR-code vaccination certificates linked with passport numbers.',
      longDescription: 'Surokkha is the official national immunization and health verification platform managed by the Directorate General of Health Services (DGHS) and ICT Division. Citizens and migrant workers can verify vaccination records, link passport details, and download digitally signed QR-coded certificates for international travel.',
      tags: ['Bangladesh', 'Surokkha', 'Vaccine Certificate', 'Health Services', 'Govt Portal'],
      iconBg: '#2563eb',
      iconText: '💉',
      bannerGradient: 'linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)',
      keyFeatures: [
        'Download Verified COVID-19 Vaccination Certificate PDF',
        'Passport-Linked QR Code Health Documentation for Travel',
        'Vaccine Status Verification for Foreign Travel & Visas',
        'Official Directorate General of Health Services (DGHS) Platform',
      ],
    },
    {
      slug: 'bd-national-portal',
      name: 'Bangladesh National Web Portal',
      url: 'https://bangladesh.gov.bd',
      domain: 'bangladesh.gov.bd',
      categoryId: govtCategory.id,
      pricing: Pricing.FREE,
      rating: 4.7,
      upvotes: 1350,
      featured: false,
      description: 'Central portal of the Government of Bangladesh connecting citizens to all ministries, public departments, e-services, and citizen charters.',
      longDescription: 'The Bangladesh National Web Portal (তথ্য বাতায়ন) is the single gateway to over 500+ government ministry websites, directorates, citizen charter forms, official government gazettes, emergency hotlines (999, 333, 109), and district administration contacts across Bangladesh.',
      tags: ['Bangladesh', 'National Portal', 'All Ministries', 'Citizen Charters', 'e-Services'],
      iconBg: '#15803d',
      iconText: '🏛️',
      bannerGradient: 'linear-gradient(135deg, #15803d 0%, #14532d 100%)',
      keyFeatures: [
        'Directory of 500+ Official Bangladesh Government Ministries',
        'Access All Citizen Service Forms, Circulars & Gazettes',
        'Emergency Hotlines (999, 333, 109) & Public Information',
        'District, Upazila, & Union Parishad Administration Directory',
      ],
    },
    {
      slug: 'bd-nbr-etin-incometax',
      name: 'NBR e-TIN Registration & Tax Return',
      url: 'https://secure.incometax.gov.bd',
      domain: 'secure.incometax.gov.bd',
      categoryId: govtCategory.id,
      pricing: Pricing.FREE,
      rating: 4.7,
      upvotes: 1080,
      featured: false,
      description: 'Official National Board of Revenue (NBR) system for instant 12-digit e-TIN registration, certificate verification, and online income tax returns.',
      longDescription: 'The National Board of Revenue (NBR) electronic tax platform allows Bangladeshi individual and corporate taxpayers to register for a 12-digit e-TIN instantly using NID, verify tax certificates, access e-Return filing portals, and submit annual tax documentation.',
      tags: ['Bangladesh', 'NBR', 'e-TIN', 'Tax Return', 'Income Tax', 'Govt Portal'],
      iconBg: '#b91c1c',
      iconText: '💰',
      bannerGradient: 'linear-gradient(135deg, #b91c1c 0%, #991b1b 100%)',
      keyFeatures: [
        'Instant 12-Digit Taxpayer Identification Number (e-TIN)',
        'Verify Existing e-TIN Certificate & Registration Status',
        'Online Income Tax Return Submission & Assessment Slips',
        'Official National Board of Revenue (NBR) Portal',
      ],
    },
    {
      slug: 'bd-police-clearance-certificate',
      name: 'Police Clearance Certificate (Online PCC)',
      url: 'https://pcc.police.gov.bd',
      domain: 'pcc.police.gov.bd',
      categoryId: govtCategory.id,
      pricing: Pricing.FREE,
      rating: 4.8,
      upvotes: 1560,
      featured: false,
      description: 'Official Bangladesh Police portal to apply and verify digital Police Clearance Certificates (PCC) required for foreign travel, jobs, and immigration.',
      longDescription: 'The Online Police Clearance Certificate system by Bangladesh Police enables citizens residing in Bangladesh or abroad to apply for criminal background verification, track verification by Special Branch (SB), and download officially verified certificates required for overseas employment, immigration, and visa stamping.',
      tags: ['Bangladesh', 'Police Clearance', 'Special Branch', 'Visa Requirement', 'PCC'],
      iconBg: '#1e40af',
      iconText: '👮',
      bannerGradient: 'linear-gradient(135deg, #1e40af 0%, #1e3a8a 100%)',
      keyFeatures: [
        'Online Police Clearance Certificate Application for Citizens & Expats',
        'Real-time Application Status Tracking by Tracking ID',
        'Digitally Signed and QR-Code Verified Official Certificate',
        'Mandatory Verification for Overseas Employment & Visas',
      ],
    },
    {
      slug: 'bd-probashi-kallyan-bank',
      name: 'Probashi Kallyan Bank (PKB)',
      url: 'http://pkb.gov.bd',
      domain: 'pkb.gov.bd',
      categoryId: govtCategory.id,
      pricing: Pricing.FREE,
      rating: 4.6,
      upvotes: 970,
      featured: false,
      description: 'Specialized state-owned bank providing low-interest migration loans, returnee rehabilitation financing, and remittance services for migrant workers.',
      longDescription: 'Probashi Kallyan Bank (PKB) is a specialized government bank established to financially empower Bangladeshi migrant workers. PKB offers low-interest migration travel loans (অভিবাসন ঋণ) to cover visa and travel expenses, returnee rehabilitation loans (পুনর্বাসন ঋণ), and reliable wage remittance transfer facilities.',
      tags: ['Bangladesh', 'Probashi Bank', 'Expatriate Loan', 'Remittance', 'Rehabilitation'],
      iconBg: '#0f766e',
      iconText: '🏦',
      bannerGradient: 'linear-gradient(135deg, #0f766e 0%, #115e59 100%)',
      keyFeatures: [
        'Migration Loan (অভিবাসন ঋণ) for Aspiring Migrant Workers',
        'Returnee Migrant Rehabilitation Loan (পুনর্বাসন ঋণ)',
        'Low-Cost Fast Remittance Inward Transfer Services',
        'Specialized Banking Services for Expatriate Families',
      ],
    },
    {
      slug: 'visit-saudi-evisa',
      name: 'Visit Saudi Official eVisa Portal',
      url: 'https://visa.visitsaudi.com',
      domain: 'visa.visitsaudi.com',
      categoryId: govtCategory.id,
      pricing: Pricing.PAID,
      rating: 4.9,
      upvotes: 1430,
      featured: false,
      description: 'Official Saudi Tourism Authority platform for issuing and checking multiple-entry tourist eVisas, Umrah permissions, and transit visas.',
      longDescription: 'The official Visit Saudi portal allows eligible international travelers and GCC residents to obtain electronic tourist visas, check visa validity, perform Umrah, explore sacred and heritage sites across Saudi Arabia, and verify tourist visa requirements.',
      tags: ['Saudi Arabia', 'Tourist Visa', 'eVisa', 'Umrah', 'Visit Saudi'],
      iconBg: '#047857',
      iconText: '🕋',
      bannerGradient: 'linear-gradient(135deg, #047857 0%, #064e3b 100%)',
      keyFeatures: [
        'Instant 1-Year Multiple-Entry Tourist eVisa Application',
        'Permits Performing Umrah & Visiting All Saudi Cities',
        'Check Visa Status & Eligibility by Passport Number',
        'Official Saudi Tourism Authority Platform',
      ],
    },
  ]

  // 3. Upsert websites and tag relations into Neon PostgreSQL
  for (const site of bangladeshWebsites) {
    const { tags, ...websiteData } = site

    const createdSite = await prisma.website.upsert({
      where: { slug: site.slug },
      update: {
        ...websiteData,
        tags: {
          set: [],
          connectOrCreate: tags.map((tagName) => ({
            where: { name: tagName },
            create: { name: tagName, slug: tagName.toLowerCase().replace(/[^a-z0-9]+/g, '-') },
          })),
        },
      },
      create: {
        ...websiteData,
        tags: {
          connectOrCreate: tags.map((tagName) => ({
            where: { name: tagName },
            create: { name: tagName, slug: tagName.toLowerCase().replace(/[^a-z0-9]+/g, '-') },
          })),
        },
      },
    })

    console.log(`✅ Upserted: ${createdSite.name} (${createdSite.slug})`)
  }

  const count = await prisma.website.count()
  console.log(`\n🎉 Successfully seeded! Total websites in Neon database: ${count}`)
}

main()
  .catch((e) => {
    console.error('❌ Error during Bangladesh portals seeding:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
